# Generated by Django 4.2.13 on 2024-06-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Compétences', models.TextField()),
                ('grade', models.CharField(max_length=100)),
                ('diplome_obtenu', models.CharField(db_column='diplome obtenu', max_length=255)),
                ('institution', models.CharField(max_length=100)),
                ('attachments', models.BinaryField()),
            ],
            options={
                'db_table': 'cv fs transformation - assurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CVBanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Compétences', models.TextField()),
                ('grade', models.CharField(max_length=100)),
                ('diplome_obtenu', models.CharField(db_column='diplome obtenu', max_length=255)),
                ('institution', models.CharField(max_length=100)),
                ('attachments', models.BinaryField()),
            ],
            options={
                'db_table': 'cv fs transformation - banque',
                'managed': False,
            },
        ),
    ]
