# Generated by Django 4.2.13 on 2024-08-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_client_alter_mission_code_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='gfis_sub_management_unit',
            field=models.CharField(blank=True, default='Transfo FS', max_length=100),
        ),
        migrations.AddField(
            model_name='mission',
            name='gpn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
