# Generated by Django 4.2.13 on 2024-08-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_mission_gfis_sub_management_unit_mission_gpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date_debut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_fin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
