# Generated by Django 4.2.13 on 2024-08-14 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0004_alter_mission_date_debut_alter_mission_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='assigned_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_debut',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_fin',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
