# Generated by Django 4.2.13 on 2024-08-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_mission_assigned_manager_alter_mission_date_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='gpn',
        ),
    ]
