# Generated by Django 4.2.13 on 2024-08-17 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0006_remove_mission_gpn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='assigned_manager',
        ),
        migrations.AddField(
            model_name='mission',
            name='partner_responsable',
            field=models.ForeignKey(limit_choices_to={'poste': 'Partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnered_missions', to=settings.AUTH_USER_MODEL, verbose_name='Partner Responsable'),
        ),
        migrations.AddField(
            model_name='mission',
            name='responsable_manager',
            field=models.ForeignKey(limit_choices_to={'poste': 'Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
