# Generated by Django 4.2.13 on 2024-08-17 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0007_remove_mission_assigned_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='responsable_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_managed', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Manager'),
        ),
    ]
