# Generated by Django 4.2.13 on 2024-08-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_client_alter_mission_code_projet_and_more'),
        ('collaborateurs', '0002_collabfs_compétences_collabfs_cv_collabfs_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabfs',
            name='grade',
        ),
        migrations.AddField(
            model_name='collabfs',
            name='missions',
            field=models.ManyToManyField(to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='collabfs',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collabfs',
            name='diplome_obtenu',
            field=models.CharField(blank=True, db_column='diplome obtenu', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collabfs',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collabfs',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
