# Generated by Django 4.2.13 on 2024-08-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('collaborateurs', '0005_collabmission_groups_collabmission_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabmission',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='collabmission',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='collabfs',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='collabfs_groups', related_query_name='collabfs_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='collabfs',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='collabfs_user_permissions', related_query_name='collabfs_user_permission', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='collabmission',
            name='role_sur_mission',
            field=models.CharField(max_length=100),
        ),
    ]
