# Generated by Django 4.2.13 on 2024-08-17 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0006_remove_collabmission_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabmission',
            name='collab',
        ),
        migrations.RemoveField(
            model_name='collabmission',
            name='role_sur_mission',
        ),
        migrations.AddField(
            model_name='collabmission',
            name='delivery_team',
            field=models.ForeignKey(blank=True, limit_choices_to={'poste__in': ['Junior Consultant', 'Senior Consultant', 'Assistant Manager']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_team_members', to=settings.AUTH_USER_MODEL, verbose_name='Delivery Team Member'),
        ),
        migrations.AddField(
            model_name='collabmission',
            name='marge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Marge (%)'),
        ),
    ]
