# Generated by Django 4.2.13 on 2024-08-17 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0007_remove_collabmission_collab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabmission',
            name='marge',
        ),
        migrations.AddField(
            model_name='collabmission',
            name='marge_mission',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Marge Mission (heures)'),
        ),
    ]
