# Generated by Django 4.2.13 on 2024-08-17 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0008_remove_collabmission_marge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabfs',
            name='hours_left',
            field=models.IntegerField(blank=True, default=40, help_text='Heures restantes que le collaborateur peut travailler cette semaine', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
