# Generated by Django 4.2.13 on 2024-08-17 16:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0009_collabfs_hours_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabmission',
            name='manager_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_missions_managed', to=settings.AUTH_USER_MODEL, verbose_name='Manager Responsable'),
        ),
        migrations.AddField(
            model_name='collabmission',
            name='marge_mission_manager',
            field=models.IntegerField(blank=True, default=0, help_text='Heures assignées au manager pour cette mission', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
