# Generated by Django 4.2.13 on 2024-08-22 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0010_collabmission_manager_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabmission',
            name='marge_mission_manager',
            field=models.IntegerField(blank=True, help_text='Heures assignées au manager pour cette mission', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
