# Generated by Django 4.2.13 on 2024-08-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0011_alter_collabmission_marge_mission_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabfs',
            name='nom',
        ),
        migrations.AddField(
            model_name='collabfs',
            name='isActivated',
            field=models.BooleanField(default=False),
        ),
    ]
