# Generated by Django 4.2.13 on 2024-08-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0012_remove_collabfs_nom_collabfs_isactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabfs',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collabfs',
            name='isActivated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collabfs',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
