# Generated by Django 4.2.13 on 2024-08-22 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet_pfe', models.CharField(max_length=255)),
                ('etat_avancement', models.IntegerField(choices=[(0, '0% - 25%'), (25, '26% - 50%'), (50, '51% - 75%'), (75, '76% - 100%')], default=0)),
                ('fichier', models.FileField(upload_to='fichiers_stagiaires/')),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagiaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
