# Generated by Django 4.2.13 on 2024-08-26 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stagiaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='etat_avancement',
            field=models.IntegerField(choices=[(0, '0% - 25%'), (25, '26% - 50%'), (50, '51% - 75%'), (75, '76% - 100%'), (100, 'Terminé')], default=0),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='fichiers_stagiaires/'),
        ),
    ]
